version: "3.8"

services:
  backend:
    image: GooGaaGee/HelpDesk-backend:latest
    restart: always
    environment:
      PORT: 5000
      CONNECTION_URL: mongodb+srv://googaagee:googaagee@cluster0.ndo7w.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      JWT_SECRET: secret#text
      NODE_ENV=development
    ports:
      - "3016:3015"

  frontend:
    image: GooGaaGee/HelpDesk-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "3001:3001"